default_language_version:
  python: python3
files: |
  (?x)^(
    byop|
    tests
  )/.*\.py$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        files: ".*"
      - id: check-case-conflict
        files: ".*"
      - id: check-merge-conflict
        files: ".*"
      - id: check-yaml
        files: ".*"
      - id: end-of-file-fixer
        files: ".*"
        types: ["yaml"]
      - id: check-toml
        files: ".*"
        types: ["toml"]
      - id: debug-statements
        files: '^byop/.*\.py$'
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        additional_dependencies:
          - "attrs"
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        args: ["--config=pyproject.toml"]
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.2
    hooks:
      - id: pycln
        name: Remove unused imports
        args: ["--config=pyproject.toml"]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.19.2
    hooks:
      - id: check-github-workflows
        files: '^github/workflows/.*\.ya?ml$'
        types: ["yaml"]
      - id: check-dependabot
        files: '^\.github/dependabot\.ya?ml$'
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.37.1
    hooks:
      - id: commitizen
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.174
    hooks:
      - id: ruff