name: create-release
on:
  workflow_dispatch:
   inputs:
    latest:
      description: "Set as the latest version"
      required: false
      default: true
permissions:
  contents: write
jobs:
  build-sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: "Build the sdist"
        run: |
          python -m pip install build
          python -m build -s
      - name: "Upload build"
        uses: actions/upload-artifact@v2
        with:
          name: sdist
          path: dist/*.tar.gz

  deploy-docs:
    runs-on: ubuntu-latest
    needs:
      - "build-sdist"  # We only want to deploy docs if the sdist was built
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: "Install dependancies"
        run: python -m pip install -e ".[dev]"
      - name: "Build Docs"
        run: mike deploy --push
