name: release
on:
  workflow_dispatch:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: "Install dependancies"
        run: python -m pip install -e ".[dev]"
      - name: "Build Docs"
        run: mike deploy --push
