name: Tests

on:
  # Disabled for now essentially
  workflow_dispatch:

env:

  package-name: byop
  test-dir: tests
  extra-requires: "[dev]"  # "" for no extra_requires

  # Arguments used for pytest
  pytest-args: >-
    -v
    --log-level=DEBUG

jobs:
  test:

    name: ${{ matrix.python-version }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash # Default to using bash on all

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: pyproject.toml

    - name: Install ${{ env.package-name }}
      run: |
        python -m pip install -e ".${{ env.extra-requires }}"

    - name: Tests
      run: |
        pytest ${{ env.pytest-args }} ${{ env.test-dir }}
